### PR TITLE
Add support for Rego syntax

### PR DESCRIPTION
**Pull request by jamietanna**
Adapted heavily from several of the lexers in this repo, and
https://github.com/tsandall/vim-rego/blob/b47bf95996b72d630464b44ca567f2945bd37ac9/syntax/rego.vim

### CODE REVIEW

**Comment by jamietanna** [comment]
Argh sorry @alecthomas  it looks like this hasn't actually worked OK - it looks like some of the text doesn't get recognised correctly.

2024-01-22-212019_1445x673_scrot

Any hints as what best to do here?

Happy to revert this PR until we've fixed it!

**Comment by alecthomas** [comment]
No worries

I'd add a test and iterate until it passes

**Comment by jamietanna** [comment]
Interesting, thanks - will give that a go tomorrow!

**Comment by alecthomas** [comment]
FYI you can also use the chroma CLI to manually test your lexer: `chroma --lexer <file.xml> <input>`

**Comment by jamietanna** [comment]
Thanks I had actually been doing that 🫣 but I changed themes to improve the output, but should have gone back to the default so I knew I'd not finished it off

**Pull request merged**
