### PR TITLE
Add basic lexer for console

### LINKED ISSUE #137: Add console lexer
It looks like the shell session lexers are a bit more difficult than using pygments2chroma, but these lexers are very nice for writing tutorials with example shell commands, especially BashSessionLexer.

Example of the difference:

console
```console
$ sudo su
# echo "foo"
foo
```

bash
```bash
$ sudo su
# echo "foo"
foo
```

### PR DESCRIPTION
**Pull request by davidofferman**
Adds support for a basic console lexer.

Fixes #137

### CODE REVIEW

**Comment by alecthomas** [comment]
I like the idea, but this doesn't give highlighting for commands at all. I feel like it would be preferable to default to bash, and other shell-specific console lexers (eg. `fish-console`) could be added later.

**Comment by chalin** [comment]
@davidofferman - thanks for much for submitting this.
@alecthomas - is it difficult to have a lexer default to another (I haven't looked at any of the code yet). Might you have an example to point us to?

**Comment by alecthomas** [comment]
Yeah take a look at the chroma.DelegatingLexer, that is probably what you want.

**Comment by chalin** [comment]
Thanks @alecthomas.
@davidofferman - is this something you have time to look into?

**Comment by alecthomas** [comment]
No response.

**Pull request closed without merging**
