### PR TITLE
Adding Pascal Lexer (WIP)

### PR DESCRIPTION
**Pull request by serhack**

### CODE REVIEW

**Comment by alecthomas** [comment]
As per the other PR, would you be able to add a test? I'm trying to have all new lexers include tests so we can detect regressions.

**Comment by alecthomas** [comment]
Thanks for all the contributions BTW :)

**Comment by alecthomas** [comment]
No response, feel free to reopen.

**Comment by serhack** [comment]
I have no time, if anyone wants to open a new PR and adds tests, feel free to do it! :)

**Pull request closed without merging**
