### PR TITLE
Add ABAP lexer

### LINKED ISSUE #278: ABAP Syntax Support
**What problem does this feature solve?**

Makes .abap files readable. 

**What feature do you propose?**

Add support for the programming language ABAP.

image

(Sorry that the comments are in german, but I think you'll get the point)

### PR DESCRIPTION
**Pull request by Jos512**
This PR adds the ABAP lexer to Chroma. I based it on the lexer that's already [in Pygments](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/business.py).

To validate I used code [from the issue](https://github.com/alecthomas/chroma/issues/278) and a piece from [this GitHub code](https://github.com/Stegosawr/archiving_engine/blob/master/src/session/zcl_archive_session.clas.abap). There were no error classes and seemingly everything seems to match well:

abap-highlight-example

(Of course the CSS colours I used could be prettier.)

Feedback or suggestions are of course more than welcome.

Closes #278

### CODE REVIEW

**Comment by Stegosawr** [comment]
You can check out this [tweet ](https://twitter.com/LarsHvam/status/1174592363534135297) if you need anything more or look at the comment I wrote on the issue. But definetly look much better now, but I would also change colours :)

**Comment by alecthomas** [comment]
Thanks!

**Comment by alecthomas** [comment]
@Stegosawr colours depend on the selected colour scheme.

**Comment by Stegosawr** [comment]
Thanks alot for the quick enhancement :)

**Pull request merged**
