### PR TITLE
Add support for more complex command prompts

### PR DESCRIPTION
**Pull request by qtc-de**
The bashsession lexer did only recognize command prompts starting with
one of the characters ``#$%>``. This commit adds support for a prefixed
block of the form ``[.*]``, which is a common layout for command prompts.

The highlighting could accidentally trigger on text starting with something like ``[+] $`` but I guess this is okay. To make it more restrictive, one could also thing about removing the spaces between the last closing bracket and the special prompt character ``#$%>``. If this is desired, I could change it.

Furthermore, one could also think about changing the highlighting of the command output. The current highlighting for the command output is ``GenericOutput``, which seems to leave the output just in ordinary text color. This makes it hard to distinguish from surrounding text. Maybe it would be better to choose a dedicated highlighting for that, as it is done by GitHub:

```console
[test@test]$ echo 'Hello World'  # echoed text appears in blue
Hello World 
```

However, I'm not familiar with your default styles and themes and not sure which highlighting option would be the best. If you have a suggestion, just mention it and I will add it to this PR :)

Best regards,
Tobias

### CODE REVIEW

**Comment by alecthomas** [comment]
Can you add a test for this please? See lexers/README for details.

**Comment by alecthomas** [comment]
The command output is highlighted by the bash lexer. eg. if you use `$ echo "hello world"` you will see the quoted string highlighted. Any improvements should go into that lexer.

**Comment by alecthomas** [comment]
Sorry I misread, I see you were referring to _output_. It's up to the theme what to do with the tokens and I think `GenericOutput` is pretty accurate. You should be able to override it in CSS if you wish.

**Comment by alecthomas** [comment]
Thanks!

**Comment by qtc-de** [comment]
Added test cases as requested.

Concerning the highlighting of the command output: I actually mean the output of the command, not the command itself (e.g. just the ``Hello World`` in the second line. However, I noticed that my assumption was wrong here. The ``GenericOutput`` group seems to be implemented exactly for this case. The problem was that my selected theme did not add a special color for it.

Is there any reason why certain themes do not add colors to specific syntax groups? Would it make sense to add a default color in these themes or is that not desired?

**Pull request merged**
