### PR TITLE
CFEngine 3: Added syntax highlighting for macros, promise keyword, and different string literals

### PR DESCRIPTION
**Pull request by olehermanse**
**Before:**
before

**After:**
after

### CODE REVIEW

**Comment by alecthomas** [comment]
Awesome! Would you mind adding a test?

**Comment by olehermanse** [comment]
@alecthomas I'm not sure how / what to test, but I added the example I used now in the last commit.

**Comment by alecthomas** [comment]
Perfect, thanks!

**Comment by olehermanse** [comment]
@alecthomas Thanks for your quick response and merge. Any idea when this will end up in a release of Hugo?

**Pull request merged**
