### PR TITLE
Remove whitespace tokenizing rule in markdown lexer

### LINKED ISSUE #744: Incorrect markdown link highlighting when in round brackets
**Describe the bug**

The highlighting of a markdown link does not work if there is a round bracket immediately preceding it.

image

**To Reproduce**

This can be seen in the [playground.](https://swapoff.org/chroma/playground/#eyJsYW5ndWFnZSI6Im1hcmtkb3duIiwic3R5bGUiOiJtb25va2FpbGlnaHQiLCJ0ZXh0IjoiW21hcmtkb3duIGxpbmtdKHd3dy5nb29nbGUuY29tKVxuXG4oW21hcmtkb3duIGxpbmtdKHd3dy5nb29nbGUuY29tKSlcblxuKFttYXJrZG93biBsaW5rXSh3d3cuZ29vZ2xlLmNvbSkgYW5kIGEgW3NlY29uZCBsaW5rXSh3d3cueWFob28uY29tKSlcbiIsImNsYXNzZXMiOmZhbHNlfQ)

To replicate manually just use this text when set to markdown mode.

```
[markdown link](www.google.com)

([markdown link](www.google.com))

([markdown link](www.google.com) and a [second link](www.yahoo.com))

```

### PR DESCRIPTION
**Pull request by cloudchamb3r**
fix #744 
related issue: go-gitea/gitea#32136

current markdown lexer is tokenizing by whitespace, but in markdown sytanx this implementation can cause some errors.

### CODE REVIEW

**Comment by alecthomas** [comment]
Apologies for the delay. It's not clear to me what this fixes, can you add some test data that proves it's fixing the underlying issue?

**Comment by cloudchamb3r** [comment]
Ok, I'll add it soon

**Comment by cloudchamb3r** [comment]
@alecthomas I updated my pull requests. please review again. thank you

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
