### PR TITLE
Split tsx and typescript lexers

### PR DESCRIPTION
**Pull request by tristanmenzel**
Split tsx and typescript lexers so the pure typescript lexer can handle generic arrow funcs.
eg. `const a = <T>(b:T): T => b;`

### CODE REVIEW

**Comment by alecthomas** [comment]
TSX doesn't support generic arrow funcs?

**Comment by tristanmenzel** [comment]
There is ambiguity between the generic type definitions and the jsx tags. I believe you can work around it by writing `<T extends any>(.. ) => ` but it's probably more common to use the function syntax or move it to a `.ts` file.

**Comment by alecthomas** [comment]
The build is failing BTW.

**Comment by tristanmenzel** [comment]
I'm afraid I'm a bit of a `go` newbie. It appears my build is failing because the new `tsx.go` file is not imported anywhere and that the `tsx.go` file is not imported because it does not exist in your repo yet (which appears to be how other lexers are imported)

Any suggestions?

**Comment by alecthomas** [comment]
According to the error log (at the bottom) it looks like a linter failure:

```
lexers/t/tsx.go:13: File is not `goimports`-ed (goimports)
```

**Comment by alecthomas** [comment]
Feel free to reopen once the lint issues have been fixed.

**Pull request closed without merging**
