### PR TITLE
fix: jsx and tsx render error

### PR DESCRIPTION
**Pull request by WingT**
Change-Id: I3c4c4319024cbc66eb068b84723818ec3eaf31cb

### CODE REVIEW

**Comment by WingT** [comment]
Hi @alecthomas , I found some badcases and hope you can check and accept this pr
1. render tagname with a dot init causes error in jsx files
```jsx
<React.Fragment>
```
2. render interp strings with a newline('\n') init causes error in jsx files
```tsx
codeObj.codeStr = `${prevLine !== undefined ? prevLine + '\n' : ''}${currLine}\n${
    nextLine !== undefined ? nextLine : ''
  }`
```
3. no support for generic type in tsx files
```tsx
function<type>(arg)
```
3. no support for tag like jsx in tsx files

**Comment by alecthomas** [comment]
Nice can you add tests to illustrate? See lexers/README. If there's already a test, add some sample code to the test fixture that illustrates what this fixes

**Comment by WingT** [comment]
|Path|Code Owners|Pending Approvals|Approved By|
|----|-----------|-----------------|-----------|
|*|a,b,|1/1|a,|
|a/b|a,b,|0/1||
|a/c|a,b,|0/1||

*TagOwners*
|Tag|Tag Owners|Pending Approvals|Approved By|
|---|----------|-----------------|-----------|
|*|a,b,|1/2|a,|
|a/b|a,b,|0/2||

**Comment by alecthomas** [comment]
Ping @WingT . Tests?

**Comment by alecthomas** [comment]
Ping.

**Pull request closed without merging**
