### PR TITLE
Update julia.go

### PR DESCRIPTION
**Pull request by matbesancon**
They key word is `abstract type`, `abstract` or `type` alone can be defined as new bindings

### CODE REVIEW

**Comment by matbesancon** [comment]
Tested with:
```go
package main

import (
	"github.com/alecthomas/chroma/quick"
	"os"
)

func main() {
	s := `
	struct Value
		v::Int
	end
	const r = 33
	A = zeros(3,3)
	B = rand(4,3)
	type = typeof(B)
	C = A * B'
	res = C' .+ r
	abstract v = 33
	abstract type K end
	`
	_ = quick.Highlight(os.Stdout, s, "julia", "html", "monokai")
}
```

Results in correct highlighting

**Comment by alecthomas** [comment]
Maybe dump that source in `lexers/testdata/julia.actual` then regenerate the expected output with `RECORD=true go test ./lexers`?

**Comment by matbesancon** [comment]
Sorry for the delay, just done it and  fixed the similar issue for "primitive type"

**Comment by alecthomas** [comment]
Brilliant, thanks!

**Pull request merged**
