### PR TITLE
Lexer for VHS

### PR DESCRIPTION
**Pull request by maaslalani**
Hi! We recently (today) launched a new project called VHS which involves a custom scripting language / DSL for input: https://github.com/charmbracelet/vhs

There were some requests to add a `Chroma` lexer for it so that you could do syntax highlighting. So, I've made a PR for the (simple) grammar.

We also have a tree-sitter grammar available here: https://github.com/charmbracelet/tree-sitter-vhs

Totally understand if you are not able to merge this lexer until the language becomes more widely used! Thank you for making `Chroma`!

### CODE REVIEW

**Review by caarlos0 — APPROVED** [review]

**Comment by alecthomas** [comment]
I'm happy to accept any lexers, but you would mind making it an XML lexer please? The conversion should be straightforward.

**Comment by alecthomas** [comment]
VHS looks cool, I have some uses for that :)

**Comment by maaslalani** [comment]
> I'm happy to accept any lexers, but would mind making it an XML lexer please? The conversion should be straightforward.

Hey, yes of course! I will do that today!

**Comment by jolheiser** [comment]
@maaslalani Is this all of the keywords/names? Just wondering because I see a few more in
https://github.com/charmbracelet/vhs/blob/2bf729bd02d40c5a68f4db11b622038b0f4f4c66/token.go#L65-L100

**Comment by maaslalani** [comment]
Ah good catch @jolheiser I definitely missed a few, I will add them in the XML lexer! Thanks!

**Comment by maaslalani** [comment]
@alecthomas Switched over to XML parsers, thanks for the great project!

**Comment by alecthomas** [comment]
Merged, thanks.

**Pull request merged**
