### PR TITLE
Add table styled line numbers

### LINKED ISSUE #52: Add table styled line numbers
See https://github.com/gohugoio/hugo/issues/3915

### PR DESCRIPTION
**Pull request by bep**
Fixes #52

### CODE REVIEW

**Comment by bep** [comment]
Notes:

I have added `highlighttable´ class to the table. This matches Pygments, but I have not added any styles to it. Pygments also has a class on both the td's (linenos, code), but I dropped that.

**Comment by alecthomas** [comment]
I think the output is not quite right. Have you checked it?

I see this with no tables:
image

And this with tables:
image

**Comment by bep** [comment]
> Have you checked it?

Yes. But it depends on what you mean by "not quite right". If you mean "not same", you are right.

**Comment by alecthomas** [comment]
The version with tables has the line numbers seemingly (ie. visibly) off by one. Notice that LANGS is almost on line 2 in the second example.

 My guess is it's something to do with vertical padding/margin.

**Comment by bep** [comment]
Yes, I can make the padding the same, but could you shed some light on my bullet 2) above. I.e. how do you handle CSS diffs from "invoking the CLI with different params". Ideally I want to have a mix of table and inline styled line number types and have one stylesheet to match them both.

Right now it is:

```css
/* LineNumbers */ .chroma .ln { color: #7f7f7f; margin-right: 0.4em; padding: 0 0.4em 0 0.4em;; display: block; }
```

Which I notice also contains an error, which I will fix.

The same with inline line numbers:

```bash
/* LineNumbers */ .chroma .ln { color: #7f7f7f; margin-right: 0.4em; padding: 0 0.4em 0 0.4em; }
```

**Comment by alecthomas** [comment]
> We should probably handle this better so people can switch between these with the same stylesheet... Suggestions welcome.

Ah, sorry, it wasn't clear to me what "these" was in this context.

I haven't looked at the details, but the class might need to be special-cased for the case when lines are in a table. This should be possible in `styleToCSS()`, maybe...

**Comment by bep** [comment]
>but the class might need to be special-cased for the case

There is already a special case, but please read and understand my last post.

**Comment by alecthomas** [comment]
Why would anyone want a mix of table and inline line-number styles simultaneously? Unless there's a compelling reason, I would not want to support that.

**Comment by bep** [comment]
Define "simultaneously" ... So:

* From Pygments there are 1 stylesheet for (what they call) `inline` and `table` styled line numbers.
* Hugo supports both Chroma and Pygments.
* Hugo supports setting the "table vs inline" style on a global and per code block level
* If I want to create a Hugo theme I would want to supply some Chroma stylesheet, but it would be up to the end user if he prefers  `inline` or `table` styled line numbers
* In many cases it would make sense to use only one and stick with it, but if I want to change my mind, I want to just "toggle a switch" in a config file.

I can come up with more if you need it.

**Comment by alecthomas** [comment]
> Ideally I want to have a mix of table and inline styled line number types and have one stylesheet to match them both.

This statement sounds to me like you wanted to have code blocks with inline numbers and code blocks with table numbers in the same page at the same time. That is what I was referring to.

From my perspective, as long as the HTML and CSS output by Chroma result in a decent-looking rendered output, I'm happy. Anything beyond that I don't really care about that much, but if you want to come up with a clean way to support both with the same CSS, go for it. If you'd prefer to output different CSS for each, based on the formatter options, then do that.

**Comment by bep** [comment]
>This statement sounds to me like you wanted to have code blocks with inline numbers and code blocks with table numbers in the same page at the same time. That is what I was referring to.

This is not me wanting things. And the above sounds like something "someone wants". I will have a look at a way to fix this.

**Comment by bep** [comment]
No table: 

image

With table: 

image

I have taken another stab at this. A couple of things to notice:

1. There is a tab diff in the above screenshots. The tab width used is 4, but in the "non table" variant this looks to include the line numbers, which does not make much sense to me. 
2. I looked at the Pygments "way of doing this", but that looked messy, and the classes used are not included in the Pygments stylesheets, so I just made up a couple of new CSS classes.

Let me know of any objections ...

**Comment by alecthomas** [comment]
Looks great, thanks @bep!

**Pull request merged**
