### PR TITLE
Add hlb lexer

### PR DESCRIPTION
**Pull request by hinshun**
Hi @alecthomas, just wanted to experiment with various syntax highlighting libraries for [HLB](https://github.com/openllb/hlb), a language I'm writing using participle.

I noticed that chroma doesn't seem to like the non-capturing group:
```go
{`(\b((?!(scratch|image)\b)[a-zA-Z_][a-zA-Z0-9]*\b))`, ByGroups(NameOther), nil},
```
chroma-hlb

The equivalent from pygments:
```python
(u'(\\b((?!(scratch|image)\\b)[a-zA-Z_][a-zA-Z0-9]*\\b))', bygroups(Name.Variable)),
```
pygments-hlb

I also included a `pygments2chroma.hlb` that allowed me to containerize the workflow to convert my pygments lexer, happy to exclude it.

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks! Try using `chroma --trace` to debug which rules are matching.

**Comment by hinshun** [comment]
I looked at haxe's example of using non-capturing group and updated my lexer to work for both pygments and chroma.

chroma-hlb

**Comment by alecthomas** [comment]
Nice! Can you add a test please? Instructions are in the lexers directory.

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
