### PR TITLE
Add shebang

### PR DESCRIPTION
**Pull request by vanillajonathan**
Add a shebang to the Python scripts.

### CODE REVIEW

**Comment by walles** [comment]
If you could `chmod a+x` them as well that would make them runnable from the command line.

**Comment by alecthomas** [comment]
Agreed, it doesn't really achieve anything without being executable.

**Comment by vanillajonathan** [comment]
But when I run Python scripts, I usually `chmod +x` first before I run them as `./script.py` instead of running `python3 script.py`. I am sure there are others who do this too.

**Comment by walles** [comment]
You should:
1. `chmod a+x` on the scripts
2. `git commit` both scripts
3. `git push` that change to this branch

`git` tracks the executable bit, so if you want them executable you should commit *after* making them executable.

**Comment by vanillajonathan** [comment]
I just edited them on GitHub on the web. Maybe this could be merged anyway? You could `chmod` them or a maintainer could edit this PR.

**Pull request merged**
