### PR TITLE
Svelte Lexer Improvements

### PR DESCRIPTION
**Pull request by CIAvash**
An Improved version of #458

### CODE REVIEW

**Comment by CIAvash** [comment]
Why did the tests fail this time? I ran the linter as well.

While testing style's lang tag, I realized SCSS is [broken](https://github.com/pygments/pygments/blob/3f6244bc1d63674c4290d570ab3676040f2189ee/pygments/lexers/css.py#L647-L649), and SASS doesn't capture whitespace and they are shown as errors :disappointed:

**Comment by alecthomas** [comment]
I think you're going to need to log into Circle, I'm not going to keep copying and pasting error messages 😀

**Comment by alecthomas** [comment]
I've merged #458, I missed it somehow. Sorry about the conflicts.

**Comment by alecthomas** [comment]
Nice! LGTM

**Pull request merged**
