### PR TITLE
Added pony lexer

### PR DESCRIPTION
**Pull request by thomastay**
Ported from Pygments, with a few minor tweaks. I've tested it on some Pony code and it seems to highlight it well.

### CODE REVIEW

**Comment by thomastay** [comment]
I'm not really sure how to add relevant tests, though I think that's probably useful. Let me know. So far, I've only done my own testing (by using it in my personal Hugo build)

**Comment by alecthomas** [comment]
Tests would be excellent, thanks. lexers/README.md describes how to do so.

**Comment by thomastay** [comment]
PTAL. I looked through the generated pony.expected file and found that it matches what I expected.

**Comment by alecthomas** [comment]
Nice, thanks!

**Pull request merged**
