### PR TITLE
Added lexer for Vue.

### PR DESCRIPTION
**Pull request by colin3dmax**

### CODE REVIEW

**Comment by alecthomas** [comment]
Excellent! Would you mind adding a test fixture for this as per the [README](https://github.com/alecthomas/chroma/blob/master/lexers/README.md)?

**Comment by colin3dmax** [comment]
OK，I will add a test.

**Comment by alecthomas** [comment]
I'm not sure if you're having issues with imports, but if you are someone wrote a [very helpful guide](https://medium.com/@sasom/how-to-fork-go-packages-f863e370bbb6) on how to fork Go packages which you might find useful.

**Comment by colin3dmax** [comment]
I am a new golang user. Thank you for your helpful guide.
When I wrote the test,I have a problem.
I read the [README](https://github.com/alecthomas/chroma/blob/master/lexers/README.md),but I don't know how to test in lexers dir.
I try
```bash
cd lexers
go test ./lexers_test.go 
ok      command-line-arguments  (cached)
```

How to test in right way?

**Comment by alecthomas** [comment]
You should be able to run the tests from the top-level directory by doing this:

```
$ go test ./...
go test ./...
ok  	github.com/alecthomas/chroma	0.016s
?   	github.com/alecthomas/chroma/cmd/chroma	[no test files]
ok  	github.com/alecthomas/chroma/formatters	0.016s
ok  	github.com/alecthomas/chroma/formatters/html	0.024s
ok  	github.com/alecthomas/chroma/lexers	(cached)
?   	github.com/alecthomas/chroma/lexers/a	[no test files]
?   	github.com/alecthomas/chroma/lexers/b	[no test files]
?   	github.com/alecthomas/chroma/lexers/c	[no test files]
?   	github.com/alecthomas/chroma/lexers/circular	[no test files]
?   	github.com/alecthomas/chroma/lexers/d	[no test files]
?   	github.com/alecthomas/chroma/lexers/e	[no test files]
?   	github.com/alecthomas/chroma/lexers/f	[no test files]
ok  	github.com/alecthomas/chroma/lexers/g	(cached)
?   	github.com/alecthomas/chroma/lexers/h	[no test files]
?   	github.com/alecthomas/chroma/lexers/i	[no test files]
?   	github.com/alecthomas/chroma/lexers/internal	[no test files]
?   	github.com/alecthomas/chroma/lexers/j	[no test files]
?   	github.com/alecthomas/chroma/lexers/k	[no test files]
?   	github.com/alecthomas/chroma/lexers/l	[no test files]
?   	github.com/alecthomas/chroma/lexers/m	[no test files]
?   	github.com/alecthomas/chroma/lexers/n	[no test files]
?   	github.com/alecthomas/chroma/lexers/o	[no test files]
?   	github.com/alecthomas/chroma/lexers/p	[no test files]
?   	github.com/alecthomas/chroma/lexers/q	[no test files]
?   	github.com/alecthomas/chroma/lexers/r	[no test files]
?   	github.com/alecthomas/chroma/lexers/s	[no test files]
?   	github.com/alecthomas/chroma/lexers/t	[no test files]
?   	github.com/alecthomas/chroma/lexers/v	[no test files]
?   	github.com/alecthomas/chroma/lexers/w	[no test files]
?   	github.com/alecthomas/chroma/lexers/x	[no test files]
?   	github.com/alecthomas/chroma/lexers/y	[no test files]
ok  	github.com/alecthomas/chroma/quick	0.020s [no tests to run]
?   	github.com/alecthomas/chroma/styles	[no test files]
```

**Comment by alecthomas** [comment]
Thanks for adding the tests, I appreciate it.

**Comment by colin3dmax** [comment]
I add a new pull request

**Comment by colin3dmax** [comment]
> I'm not sure if you're having issues with imports, but if you are someone wrote a [very helpful guide](https://medium.com/@sasom/how-to-fork-go-packages-f863e370bbb6) on how to fork Go packages which you might find useful.

Very useful for me,Thank you!

**Pull request closed without merging**
