### PR TITLE
Add SuperCollider lexer

### PR DESCRIPTION
**Pull request by kflak**
Following up on [this issue](https://github.com/alecthomas/chroma/issues/368).

I followed the instructions in the main README to create the branch. I don't really have a way of testing this on my machine (mostly due to a lack of skillset :-)), so there is a fair chance something is not right. If so I'd be happy to try and sort out the ugly, but I'd probably need a bit of help.

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks! Tests are failing, but also if you could add tests (it's simple) by following the instructions in lexers/README.md.

**Comment by kflak** [comment]
Hey there, will try to get on this tomorrow. However, I am a 100% noob when it comes to go programming, so I wouldn't even know where to start with this. Currently what I did was to copy a radom file with supercollider code into the lexers/testdata dir, rename it to supercollider.actual, run
```
RECORD=true go test ./lexers
```
in the project root, but I don't see any output, nor is there a supercollider.expected popping up... 
Am I even on the right track? If not, are there any resources I could check out to learn more about the specific test procedures you are using? Sorry for the extreme noobiness...

**Comment by alecthomas** [comment]
To generate the output you'll need to place some example code in `lexers/testdata/supercollider.actual`. Then when you run with `RECORD=true` it will write a `supercollider.expected` file. Check this to see if the tokens look about right, and off you go.

**Comment by kflak** [comment]
OK, think I got it now. I needed to put the supercollider.go file directly into ./lexers/, not in to ./lexers/s/ to make `go test` generate the `supercollider.expected` file. Still too much of a noob to even try running the thing, haha...

**Comment by alecthomas** [comment]
This is still not working, so I'm going to close it for now. Feel free to update the PR once you've fixed CI.

**Pull request closed without merging**
