### PR TITLE
Put lines in a div & code lines in a span, Add WrapLongLines Option

### LINKED ISSUE #549: Wrap code lines in spans; style default line numbers using CSS :before
**What problem does this feature solve?**

I use Chrome via Hugo and it would be really nice to print web pages that have long lines of code while still maintaining with line number support.

By default, long lines run off the page in print mode because it's assumed that you have an infinite ability to horizontally scroll. You can correct this with a quick CSS patch, so no big deal:

```css
/* Get rid of line numbers for print */
@media print {
    pre {
        white-space: pre-wrap;
        word-wrap: break-word;
    }
}
```

With `LineNumbersInTable()` configured, the line numbers absolutely do not line up for these wrapped, long lines:

Screen Shot 2021-09-17 at 11 09 02 PM

If you go with the default behavior, wrapping works perfectly for the printed page:

Screen Shot 2021-09-17 at 11 57 03 PM

However, we have a new problem with the default behavior: the generated line numbers are explicitly put into the code block as content. As a result, any time you attempt to copy and past code from a webpage in screen mode, you're going to copy the line numbers which is incredibly annoying and absolutely not desirable.

**What feature do you propose?**

I propose that Chroma add a new configuration function `LinesInSpan()` that would wrap every line in the `code` block inside a `span` tag.

Users could then put in their own CSS to add line numbers using `:before` and CSS counters. That, or another function `LineNumbersBeforeSpan()` could come into play to add those CSS classes.

I can just imagine that putting line numbers in spans would be useful for other things like alternating line background colors and adding a vertical rule after the line number. That's why I'm proposing that they be separate functions.

You can see an example of someone doing this in this StackOverflow post:

https://stackoverflow.com/q/40842277/7583677

The counter from the `:before` style isn't selectable because it's not content so you don't have to worry about people copying it on accident. This solves the big problem with the current approach today.

[React Syntax Highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) + [Highlight.js](https://github.com/highlightjs/highlight.js) has this figured out already and from what I can tell, the JavaScript aspects are just generating the HTML and CSS rather than interacting with it. I have an [open source code printing utility](https://jaredpetersen.github.io/codeprinter/) that uses these two projects and the produced HTML can possibly be used as a reference.

Here's some screenshots of Chrome Dev Tools opened up to the code blocks and styling:

Screen Shot 2021-09-17 at 11 44 59 PM

Screen Shot 2021-09-17 at 11 44 33 PM

Here's what a long line of code looks wrapped when you have this styling scheme:

Screen Shot 2021-09-17 at 11 50 05 PM

Switching to line-based spans also allows you to add other styling as well like a vertical ruler after the lines of code (`border-left: 1px solid black;`):

Screen Shot 2021-09-17 at 11 50 14 PM

### LINKED ISSUE #558: LineHighlight not working properly with horizontal overflow
**Describe the bug**

Hi,

I am using chroma through hugo to display code blocks on my blog. 
One issue I'm currently having is that the lines are not fully highlighted when `overflow-x: scroll` is configured.

Here's the comparison between desktop size and mobile size. On the mobile screenshot, I have scrolled a little bit to the right so you can see that the highlighting is not going completely to the end of the code block.

**Desktop**

Desktop

**Mobile**

Mobile

**To Reproduce**

1. Download this html page: https://paste.sr.ht/blob/835e85e36b57840f880e59696e17267babb9ad15 (It contains a simple code block + syntax highlighting from chroma (although I've changed the colors, but that's not important).
2. Open in browser
3. Make the window small (or use whatever browser feature to simulate small devices)
4. See that the line is highlighted only for the viewport width, but not the full overflowed width

I've been trying to find a fix for this but haven't been able to yet.. If someone with good CSS skills could help that'd be great.

The fix should probably be integrated to https://github.com/alecthomas/chroma/blob/master/formatters/html/html.go#L412 so that everyone benefits.

I've tried with `width: max-content` but that's not quite what I want.

### PR DESCRIPTION
**Pull request by CIAvash**
This pull request:
- Puts code lines in a span: `<span class="cl">...</span>`
- Puts line numbers and code lines in a div: `<div class="line"><span class="ln">...</span><span class="cl">...</span></div>`
- Adds a `WrapLongLines` option for wrapping long lines
- Adds a `PreWrapper` type for main `.chroma` class, Changes `Background` class to `bg`
- Fixes #549
- Fixes #558

I don't know if tables are needed now, unless they serve a purpose I'm not aware of.

### CODE REVIEW

**Comment by alecthomas** [comment]
Nice, have you visually verified that it renders correctly? If not don't worry about it, I'll clone the branch and push it up to the playground so we can mess around.

**Comment by alecthomas** [comment]
I [pushed it up](https://swapoff.org/chroma/playground/), looks good to me. Might be worth taking a look @bep , as this will effect Hugo's output.

**Comment by CIAvash** [comment]
> Nice, have you visually verified that it renders correctly? If not don't worry about it, I'll clone the branch and push it up to the playground so we can mess around.

Yes, of course, but I haven't tested it in all browsers. Although most of them are chromium-based now, except Firefox and Safari.

Also there might be scenarios that I'm not aware of, so it's better if other people test it as well.

**Comment by alecthomas** [comment]
LGTM, @bep can take a look asynchronously and we can iterate on any issues later.

**Pull request merged**
