### PR TITLE
Introduce the Nord theme

### PR DESCRIPTION
**Pull request by diegoholiveira**
This commit adds the Nord theme as an option. This theme is fully documented in the official website: https://www.nordtheme.com

### CODE REVIEW

**Comment by alecthomas** [comment]
Nice, thanks.

**Comment by caarlos0** [comment]
Thanks! I was going to work on this myself just now 🙏

**Comment by diegoholiveira** [comment]
> Thanks! I was going to work on this myself just now 🙏
> 
> PS: any chance we can get a release @alecthomas?

Could be a great opportunity to make sure I did the colors right ;)

**Comment by caarlos0** [comment]
Did some testing (compiled hugo using chroma's master branch and build my site) and it seems OK to me. Thanks again 🚀

**Pull request merged**
