### PR TITLE
regenerate groovy lexer from pygments upstream

### PR DESCRIPTION
**Pull request by kingdonb**
I had a look over the README and it became clearer how lexers come to be in the supported list, I believe this one came from pygments and thanks to the excellent docs, I was able to figure out roughly how to import it so we can see the diff

I ran:

```shell
python3 _tools/pygments2chroma.py \
  pygments.lexers.jvm.GroovyLexer \
  > lexers/g/groovy.go \
  && gofmt -s -w lexers/g/groovy.go
```

and made some structural changes to the output so that the diff would be more obvious.

Since there are changes to the rules I believe that I had problems with, I'm willing to bet this is going to resolve them! (ref: #588 is my issue)

### CODE REVIEW

**Comment by kingdonb** [comment]
What a wild ride. It doesn't look like this fixes anything.

I spent some time to figure out how to build chromad and run the playground locally, I have a `v0.9.4-17-g3d86184` which I can run that I think I have built from the new lexer in this PR, and it looks the same.

I'll leave this here in case I missed something obvious, maybe someone can pick it up and save some time who knows what they're doing?

**Comment by kingdonb** [comment]
* https://github.com/pygments/pygments/issues/538

Found this: I guess there is an issue open for this upstream.

**Comment by alecthomas** [comment]
Thanks for digging into it at least :)

**Comment by alecthomas** [comment]
Sorry about this, but I did a very large refactoring of Chroma to allow lexers to be generated in XML. Unfortunately this will no longer merge.

**Pull request closed without merging**
