### PR TITLE
Update Java lexer to use Punctuation where applicable (#254)

### PR DESCRIPTION
**Pull request by dpromanko**
PR for https://github.com/alecthomas/chroma/issues/254

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks for the PR, but the tests are failing.

**Comment by dpromanko** [comment]
Yeah, I was a little confused at the tests failing at first. Didn't realize there was a concept of sublexers. I'll fix the tests when I get a chance.

**Comment by dpromanko** [comment]
Sorry for not running tests locally the first time. This is the first time I've cloned and contributed to a Go project and was a little confused at how to run stuff locally. Newer to git as well, so out of curiosity is there something I should do to squash these commits, or is that something you do on merge?

**Comment by alecthomas** [comment]
No worries, thanks for contributing!

Nope I will squash them on merge. Thanks again!

**Pull request merged**
