### PR TITLE
Add WitchHazel by Thea Flowers

### PR DESCRIPTION
**Pull request by stefanv**
https://witchhazel.thea.codes/

### CODE REVIEW

**Comment by stefanv** [comment]
I have tested the addition using `go test`, but I would like to do some more testing (and visually inspect the output) before removing draft status.

Please forgive my ignorance, but I am new at go and cannot figure out how to install the binary for testing (`go build` and `go install` are both quiet).

**Comment by alecthomas** [comment]
go build will place it in the working directory

**Comment by alecthomas** [comment]
However you should add some actual tests to really be sure. Follow the README in lexers.

**Comment by stefanv** [comment]
`go build` does not produce anything as far as I can tell.  It also looks like none of the other styles have tests associated with them.

**Comment by alecthomas** [comment]
Ah sorry, I didn't read the code - the tests are for the lexers. `go build` will only produce an executable for a `main` package. I would build the chroma executable and use that:

```
go run ./cmd/chroma -s witchhazel SOMEFILE
```

**Comment by stefanv** [comment]
Thanks, @alecthomas, that's helpful.  This is where my inexperience with go is a problem; I'm sure it must be obvious, but when I run `go run ./cmd/chroma` I get:

```
go run: no packages loaded from ./cmd/chroma
```

Maybe I need some environment variable set, or a newer version of go? I have:

```
go version go1.17.3 linux/amd64
```

Feel free to just point me to a manual or website; I can teach myself if I have a rough sense of where to look.

**Comment by alecthomas** [comment]
Sorry that is my bad. I forgot that I made `chroma` a separate Go module. You'll need to do:

```
cd ./cmd/chroma
go run . -s witchhazel SOMEFILE
```

**Comment by stefanv** [comment]
This worked well, and I was able to confirm that the theme renders as expected:

**Comment by alecthomas** [comment]
Awesome, thanks :)

**Pull request merged**
