### PR TITLE
Add NSIS lexer

### LINKED ISSUE #459: [waiting] Add syntax highlighting for NSIS (.nsi, .nsh)
I can't find the "highlight" about NSIS([Nullsoft Scriptable Install System](https://nsis.sourceforge.io/Main_Page)) on [supported-languages](https://github.com/alecthomas/chroma#supported-languages)

It would be great if you could add ("nsi", "nsh") to the N class. Thanks!

Prefix | Language
:----: | --------
N | NASM, Newspeak, Nginx configuration file, Nim, Nix, ``nsi``, ``nsh``

----

👉[link](https://nsis.sourceforge.io/Category:Syntax_Highlighting) about *Contains NSIS syntax files for different text editors, browsers, and websites.*

### PR DESCRIPTION
**Pull request by serhack**
It should close #459

### CODE REVIEW

**Comment by alecthomas** [comment]
Would you be able to add a test? I'm trying to have all new lexers include tests so we can detect regressions.

**Comment by serhack** [comment]
hm, I'm not sure why it fails. On my machine:

```
ok      github.com/alecthomas/chroma/v2/lexers  4.566s
```

**Comment by alecthomas** [comment]
The expected file has tabs, while the real file has spaces. I don't know why it's passing on your machine though.

**Comment by JakobDev** [comment]
@serhack Are you still working on this?

**Comment by serhack** [comment]
I forgot about this! As soon as I have a free slot, I'll update it :)

**Comment by alecthomas** [comment]
Feel free to reopen.

**Pull request closed without merging**
