### PR TITLE
Add IPython (Python3 alias) lexer

### LINKED ISSUE #164: Should `ipython` be added as an alias to `python3` lexer?
Should code blocks like:

````
```ipython
print("hello")
```
````

also use the python3 lexer?

[Ref][1]

[1]: https://github.com/alecthomas/chroma/blob/5d7fef2ae60b501bbf28d476c3f273b8017d8261/lexers/p/python3.go#L14

### PR DESCRIPTION
**Pull request by Jos512**
This pull request adds an IPython lexer, copied from the Python3 lexer. The motivation for a separate lexer is [Alec's comment](https://github.com/alecthomas/chroma/issues/164#issuecomment-429589811) about that IPython should be treated differently than Python.

When I looked at the [official IPython doc](https://ipython.readthedocs.io/en/stable/interactive/python-ipython-diff.html), I saw there are barely any differences between them in terms of code syntax. So I based the IPython lexer on the Python 3 lexer, without change. (I of course looked for more information online, but could not find a syntax difference list between Python and IPython.)

Once we have a separate lexer for IPython, it will also be easier to make changes in the future when IPython develops/changes. And it can increase pull requests from other people once there's already a lexer framework in place.

I think it's safe to treat IPython as Python 3 for now, since other syntax highlights (like [highlight.js](https://github.com/highlightjs/highlight.js/pull/1906)) already treat IPython as an alias for Python. The [official IPython highlight](https://github.com/ipython/ipython/blob/master/IPython/lib/lexers.py) also treats the language as a subset of Python.

Another motivation I had was that I noticed that both SCSS and Sass are separate Chroma lexers, despite being nearly identical (apart from indentation rules).

(The code example in this pull request is taken from a public source, an [IPython wiki page](https://github.com/ipython/ipython/wiki/Cookbook:-Dated-logging).)

## Example of IPython highlight

ipython-example

---

Closes #164

### CODE REVIEW

**Comment by alecthomas** [comment]
It would actually be better if this (and actually also the Arduino lexer) could be refactored so they "extend" their parent lexer. You should be able to do this by creating a function that parameterises the differences. eg. if the only difference is extra keywords, a function like `MakePython(extraKeywords []string) Lexer` might do the job.

**Comment by Jos512** [comment]
That sounds like a good idea and actually makes a lot of sense.

Is there a Chroma lexer that you consider a good example of this approach? 

I ask because I couldn't figure out how to do this. Yesterday I also got blocked with issue #147, which asks for a similar approach (which I neither couldn't figure out).

**Comment by alecthomas** [comment]
I don't think there are any existing lexers that do this, but you should be able to just create a function and call it like:

```go
var Python = MakePythonLexer(nil)

var IPython = MakePythonLexer(extraIPythonKeywords)
...

**Comment by Jos512** [comment]
I took a few looks at this in the past weeks but haven't been able to figure it out. Sorry for that. I'll look to see if there's easier stuff for me to do in the future.

Have a nice weekend. :slightly_smiling_face:

**Pull request closed without merging**
