### PR TITLE
Support Fennel.

### PR DESCRIPTION
**Pull request by technomancy**
This adds support for the Fennel programming language: https://fennel-lang.org

I couldn't find much explanation for what the different lexer rules
meant, so I based it off of Clojure's lexer since the two languages
share a very similar syntax.

I also included a program to generate a list of keywords from Fennel's
own listing, which will make it easier to update in the future.

### CODE REVIEW

**Comment by alecthomas** [comment]
Nice, thanks. Can you add some test data per the README in the lexers directory?

**Comment by technomancy** [comment]
Sure; I'll give it a shot. I don't have the golang tooling installed on my machine and don't really want to go thru all that, so I'll push it out to CI and see if I can generate the `.expected` file from there.

**Comment by technomancy** [comment]
Got some help with generating the `fennel.expected` file, however, there are a lot of "error" entries in the listing. However, there's not really any context given about what the error actually is. Could you advise?

**Comment by alecthomas** [comment]
An error entry means that input text wasn't matched by any of the patterns.

**Comment by alecthomas** [comment]
BTW you should be able to install and run go automatically via ./bin/go

**Comment by technomancy** [comment]
I see; so it sounds like maybe the problem is that whitespace needs to be listed explicitly then?

I was basing this off the Clojure lexer, which doesn't do this. But maybe the Clojure lexer is broken too? https://github.com/alecthomas/chroma/blob/master/lexers/c/clojure.go I don't see any tests for it so maybe it just got overlooked?

**Comment by alecthomas** [comment]
When I initially created Chroma there was no test data, so many lexers are missing them.

However Clojure does match whitespace [here](https://github.com/alecthomas/chroma/blob/master/lexers/c/clojure.go#L23).

**Comment by technomancy** [comment]
I see. But that treats whitespace as `Text`, which I think is wrong? Shouldn't it be classifying it as whitespace instead?

**Comment by alecthomas** [comment]
Linter is failing. I'll paste it in here so you don't have to login to Circle:

> lexers/f/fennel.go:47: File is not `gofmt`-ed with `-s` (gofmt)

Just run `./bin/gofmt -w ./lexers/f/fennel.go`

**Comment by technomancy** [comment]
Looks like it doesn't support my machine.

```
~/src/chroma $ ./bin/gofmt -w ./lexers/f/fennel.go
Bootstrapping /home/phil/.cache/hermit/pkg/hermit@stable/hermit from https://github.com/cashapp/hermit/releases/download/stable
Downloading https://github.com/cashapp/hermit/releases/download/stable/hermit-linux-aarch64.gz to /home/phil/.cache/hermit/pkg/hermit@stable/hermit
curl: (22) The requested URL returned error: 404 

gzip: stdin: unexpected end of file
```

Maybe I can try it on another machine later.

**Comment by technomancy** [comment]
Quicker to just replace the spaces with tabs manually I guess...

**Comment by alecthomas** [comment]
Thanks for persisting.

Out of curiosity, what sort of machine are you running on?

**Comment by technomancy** [comment]
Thanks for your help!

I'm developing on an MNT Reform. https://mntre.com/

**Pull request merged**
