### PR TITLE
Basic lexer for Microsoft Power Query M

### PR DESCRIPTION
**Pull request by nonodename**
Hi there.

Language described at https://docs.microsoft.com/en-us/powerquery-m/m-spec-lexical-structure.

Have tested with my PQ files, hoping to get Hugo updated so the highlighting is right on my blog articles ([example](https://nonodename.com/post/powerquerywikidata/))

### CODE REVIEW

**Comment by alecthomas** [comment]
Seems reasonable, can you add a test? Instructions are in lexers/README.md.

**Comment by alecthomas** [comment]
No response.

**Comment by nonodename** [comment]
Hey Alec - never got the notification from github that you were looking for tests. Will get these created and reopen the request.

**Comment by alecthomas** [comment]
Aha! Sounds good, thanks!

**Comment by nonodename** [comment]
Should be good now Alec - thanks for your patience. First time doing anything in go :-)

**Comment by alecthomas** [comment]
Awesome, thanks!

**Pull request merged**
