### PR TITLE
Some Raku modifications and making use of #519 and #518

### PR DESCRIPTION
**Pull request by CIAvash**

### CODE REVIEW

**Comment by alecthomas** [comment]
Thanks for all the contributions recently, I appreciate it.

**Comment by CIAvash** [comment]
You're welcome, and thanks for creating Chroma. Do you have any plan on releasing a new version? I'm looking forward to using the new features in Hugo and Germanium.

**Comment by CIAvash** [comment]
@alecthomas mentioning you, just in case you missed my comment. If not, ignore my comment. 😀

**Comment by alecthomas** [comment]
I can cut a new release!

**Pull request merged**
